AllCops:
  Exclude:
    - 'spec/dummy/**/*'
  RunRailsCops: false

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Style/Encoding:
  EnforcedStyle: when_needed

Metrics/MethodLength:
  Max: 35

Style/NumericLiterals:
  MinDigits: 7

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/BlockNesting:
  Max: 4
  
Metrics/ClassLength:
  Max: 250
  
Metrics/CyclomaticComplexity:
  Max: 12

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    
Style/GuardClause:
  MinBodyLength: 4

# Maybe this can go away eventually? It seems somewhat limiting though.
Style/RaiseArgs:
  Enabled: false

Style/Next:
  Enabled: false
  
Style/Documentation:
  Enabled: false