productiont:
  servers: ["127.0.0.1"]
  port: 9042
  keyspace: "datastax_rails_development"
  strategy_options: {"RS": "3"}
  connection_options:
    timeout: 20
    retries: 3
    server_max_requests: 1000
  solr:
    port: 8983
    path: /solr

development:
  servers: ["sade-jasonk"]
  port: 9042
  ssl:
    #cert: config/datastax_rails.crt
    #key: config/datastax_rails.key
    #ca_cert: config/ca.crt
  keyspace: "datastax_rails_development"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  strategy_options: {"replication_factor": "1"}
  connection_options:
    timeout: 10
  solr:
    port: 8983
    path: /solr
    
test:
  servers: ["sade-jasonk"]
  port: 9042
  ssl:
    #cert: config/datastax_rails.crt
    #key: config/datastax_rails.key
    #ca_cert: config/ca.crt
  keyspace: "datastax_rails_test"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  strategy_options: {"replication_factor": "1"}
  connection_options:
    timeout: 30
  solr:
    port: 8983
    path: /solr
